# Basic
title: redmac
subtitle: 精诚所至 金石为开
welcome_message: <a href="www.swift.org" target="_blank">探索swift的之路</a>
description: 嗨，我是redmac,目前在上海，从事iOS开发
creator: <a href="http://redmac.github.io/">@redmac</a>

url: "http://redmac.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: 我的项目, url: 'https://github.com/redmac'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: redmac
    github: redmac
    twitter: redmac
    mail: 327930239@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
